### ISSUE TITLE
Multiple tv and movie libraries support

### ISSUE THREAD

**Issue by jl94x4** [bbrown430/plex-poster-set-helper#10]
I have different libraries for kids TV, reality TV and normal TV shows, it appears I can't reference more than 1 TV or movie library in the config?

Is this possible?

**Comment by jl94x4** [comment]
@bbrown430 Is this possible? So frustrating having to change the config for each Library before using it.

**Comment by bbrown430** [comment]
Yes it's possible, next priority. The way I use multiple libraries is for the separation of HD and 4K content. So I will need to add duplicate detection and make sure it is being applied to the correct library.

**Comment by jl94x4** [comment]
> @jl94x4 Yes it's possible, next priority. The way I use multiple libraries is for the separation of HD and 4K content. So I will need to add duplicate detection and make sure it is being applied to the correct library.

Brilliant, looking forward to it. My use case is just the separation of Reality/Kids and Drama Shows :D

I also use 4K libraries, but won't be using them for covers as I have PMM apply 4K overlays, so would rather overlays be untouched for that lib!

**Comment by bbrown430** [comment]
Latest commit added support for multiple TV libraries. Began working on multiple movies as well, but not happy with the efficiency.

To utilize it, swap the config line to `"tv_library": ["Library 1", "Library 2"],` etc.

If the same TV show is in more than one library, in the current implementation it will replace the posters of the library listed first in that array. 

Hope this helps!

**Comment by jl94x4** [comment]
Does this look right? I'm getting an error

`{
    "base_url": "http://192.168.1.22:32400",
    "token": "Hr4pPBp313soEsVSSRVm",
    "tv_library": ["TV Shows", "TV Shows - Reality", "TV Shows - Kids"],
    "movie_library": "Movies", "Movies - Kids", "Movies - Misc"]
}`

Error I get is

``Error with config.json file. Please consult the readme.md``

**Comment by bbrown430** [comment]
The syntax is correct for TV shows, but incorrect for movies. Regardless, I still need to add multi library support for movies, so keep that to one library for now. That should fix the error.

**Comment by jl94x4** [comment]
> {
    "base_url": "http://192.168.1.22:32400",
    "token": "<hidden>",
    "tv_library": ["TV Shows", "TV Shows - Reality", "TV Shows - Kids"],
    "movie_library": "Movies"
}

This currently hangs infinitely on my terminal?

**Comment by bbrown430** [comment]
The current implementation is very inefficient and I need to rethink it. It shouldn't hang infinitely though. I'm assuming you just have very large libraries, and it's taking a very long time to consolidate them into a list. I'll work on throwing something smarter together.

**Comment by jl94x4** [comment]
I do have a large Library, yeah, maybe it'll work eventually. I'll leave it for a little while

**Comment by bbrown430** [comment]
This should be fully functional now for both tv shows and movies. Obviously please let me know if you run into any errors, but I'll close the issue for now.

"tv_library": ["TV Shows", "TV Shows - Reality", "TV Shows - Kids"],
"movie_library": ["Movies", "Movies - Kids", "Movies - Misc"]

Here's the corrected syntax of the config you shared earlier. Let me know how it goes!

**Comment by jl94x4** [comment]
Hey @bbrown430 do you have discord? Could you add me? I'd like a chat if possible! 

My user name is jl94x4
