### ISSUE TITLE
mediux.pro specify title cards only

### ISSUE THREAD

**Issue by kyleviloria** [bbrown430/plex-poster-set-helper#13]
On mediux.pro, I can't find a link to title cards from a specific set - only the full set that often includes posters/covers. Perhaps there's a way to specify title cards only via python, or maybe I'm missing something on mediux.pro, or maybe mediux.pro can make specific links to title cards available since there's a button to download title cards only.

**Comment by bbrown430** [comment]
This is a good suggestion. Right now, there's no specifying, it will just update every poster that is in the set. Would this be something you'd want to set on a case by case basis, or would a global setting in the config suffice?

**Comment by kyleviloria** [comment]
I think a global setting would suffice. Thanks! I'm loving the options your program opens up for my library.

**Comment by jl94x4** [comment]
+1 on this too!
