### ISSUE TITLE
Wrong show is updated

### ISSUE THREAD

**Issue by 2bitERROR** [bbrown430/plex-poster-set-helper#14]
Trying to update House for instance and instead the script is replacing posters on The Fall of the House of Usher. Seen this with other shows with single name title where it instead updates the wrong show that contains the same word in the title.

> Enter a ThePosterDB set (or user) or a MediUX set url: https://mediux.pro/sets/17115
Uploaded cover art for House - Cover.
Uploaded background art for House.
Uploaded art for House - Season 1 Episode 1.
Uploaded art for House - Season 1 Episode 2.
Uploaded art for House - Season 1 Episode 3.
Uploaded art for House - Season 1 Episode 4.
Uploaded art for House - Season 1 Episode 5.
Uploaded art for House - Season 1 Episode 6.
Uploaded art for House - Season 1 Episode 7.
Uploaded art for House - Season 1 Episode 8.
House - 1 Episode 9 not found, skipping.
House - Season 1 not found, skipping.
House - 1 Episode 10 not found, skipping.
House - Season 1 not found, skipping.
House - 1 Episode 11 not found, skipping.
House - Season 1 not found, skipping.
House - 1 Episode 12 not found, skipping.
House - Season 1 not found, skipping.
House - 1 Episode 13 not found, skipping.
House - Season 1 not found, skipping.
House - 1 Episode 14 not found, skipping.
House - Season 1 not found, skipping.
House - 1 Episode 15 not found, skipping.
House - Season 1 not found, skipping.
House - 1 Episode 16 not found, skipping.

**Comment by bbrown430** [comment]
Resolved with latest commit
