### ISSUE TITLE
Match Shows/Movies by year

### ISSUE THREAD

**Issue by jl94x4** [bbrown430/plex-poster-set-helper#16]
For shows such as this

https://mediux.pro/sets/17377

It applies it to the 1963 show, and not the correct 2005 show. Is there a way it can use the year in the title to determine which is the correct one?

After using this tool, I've found this to be a rather common occurrence.

**Comment by bbrown430** [comment]
Already on my to do list, thank you for bringing to my attention.

**Comment by bbrown430** [comment]
@2bitERROR @jl94x4 this should be fixed with the latest commit, but can you please try it out and let me know if it persists? I unfortunately don't have any shows in my library that are similar enough for me to test with.

**Comment by jl94x4** [comment]
Testing..

**Comment by jl94x4** [comment]
Seems to be very hit and miss on the posters?

![image](https://github.com/bbrown430/plex-poster-set-helper/assets/18123855/5d0c143f-c566-4de4-8c38-8c65395cecc5)

Even though the log shows it uploaded one?

![image](https://github.com/bbrown430/plex-poster-set-helper/assets/18123855/6f7bbec0-6c53-431c-b1ed-68a07992c18b)
