### ISSUE TITLE
MediUX does not work

### ISSUE THREAD

**Issue by bbrown430** [bbrown430/plex-poster-set-helper#18]
MediUX is now returning a 500 error response for any URL. Might not be circumventable. Tried altering the request headers, but does not fix the issue.

**Comment by dlasis** [comment]
Hope this gets fixed. :(

**Comment by DouwJacobs** [comment]
I might have a possible fix for this. Tested it on shows (title cards, season posters, backgrounds and covers) and movies. Haven't tested it on Movie Collection posters. Happy to submit a PR if you are interested?

**Comment by bbrown430** [comment]
@DouwJacobs please do! Would love to take a look.

**Comment by DouwJacobs** [comment]
@bbrown430 I tried pushing to a new branch but I'm getting an authentication error 😄

**Comment by bbrown430** [comment]
@DouwJacobs If branching doesn't work maybe try forking and creating a PR from that?

**Comment by bbrown430** [comment]
@DouwJacobs your solution is working flawlessly, thank you so much for contributing! Closing for now.
