### ISSUE TITLE
Mediux links with only posters and no title cards failing

### ISSUE THREAD

**Issue by 123JackCole** [bbrown430/plex-poster-set-helper#24]
The script is failing when run on a mediux set that only contains posters. (for example, https://mediux.pro/sets/13716 or ). The failure occurs in the scrape_mediux function. script.text will not contain 'title' so poster_data will never be set and the for loops iterating through poster_data will throw an error.

![image](https://github.com/bbrown430/plex-poster-set-helper/assets/59670293/21d06206-86fd-4627-bca6-646617f17271)

![image](https://github.com/bbrown430/plex-poster-set-helper/assets/59670293/6ebde9ae-47b2-457c-864f-9ad39f700624)

**Comment by 123JackCole** [comment]
Another example url that produces the same error https://mediux.pro/sets/8113

**Comment by bbrown430** [comment]
Swamped with finals this and next week but will tackle this when I find the time. Thanks for bringing this to my attention!

**Comment by bbrown430** [comment]
this should be fixed now
