### ISSUE TITLE
Failed to retrieve page - Status 403

### ISSUE THREAD

**Issue by Lonewolf147** [bbrown430/plex-poster-set-helper#35]
I haven't ran this in a while, but it used to work great when I did.  I tried it again tonight, and I'm getting a 403 error. It doesn't matter what set I use, or if I try using bulk. Same error.

`root@Valaskjalf:/mnt/plex/PMS/binhex-plex/posters# python3 plex-poster-set-helper.py`
`Enter a ThePosterDB set (or user) or a MediUX set url: https://theposterdb.com/set/113796`
`Failed to retrieve the page. Status code: 403`

**Comment by Lonewolf147** [comment]
I also tried using a mediux address, and it is giving an error 500

`root@Valaskjalf:/mnt/plex/PMS/binhex-plex/posters# python3 plex-poster-set-helper.py`
`Enter a ThePosterDB set (or user) or a MediUX set url: https://mediux.pro/sets/7433`
`Failed to retrieve the page. Status code: 500`

**Comment by bbrown430** [comment]
@Lonewolf147 Make sure you are using the latest version. These errors have been addressed.

**Comment by Lonewolf147** [comment]
Thanks. I did re-download the zip while testing this. Didn't seem to make a difference.

Is there a way to see which version of the script I'm running, and what the latest one is?

On Jul 9, 2024, at 10:34, Brian Brown ***@***.******@***.***>> wrote:

@Lonewolf147<https://github.com/Lonewolf147> Make sure you are using the latest version. These errors have been addressed.

**Comment by bbrown430** [comment]
If you download the latest .zip and work out of there, there shouldn't be any potential for conflicts

**Comment by Lonewolf147** [comment]
Ahhh, I see the issue. I didn't know the file name changed. All the hyphens were changed to underscores. Even though I copied the new one over, I was still running the old script. Running the new one now works perfect.  Thanks!
