### ISSUE TITLE
Using the script is locking plex up completely while running

### ISSUE THREAD

**Issue by morpheus2n2** [bbrown430/plex-poster-set-helper#44]
I have noticed today to go with my other issue, that while the script is running plex will completely lock up and be unreachable, its still running fine and not using much CPU but the webui is completely dead the entire time this script is running.
Once the script is done or exited out plex returns just fine after about 20 seconds

**Comment by bbrown430** [comment]
This seems like it must be related to your setup based on the other issue. I do not have this issue on my setup and have not seen it reported elsewhere.
