### ISSUE TITLE
No module named 'requests'

### ISSUE THREAD

**Issue by pippotaz** [bbrown430/plex-poster-set-helper#45]
Hello,

I was able to run the the script without problems with GUI, but after a reboot I'm unable to launch it either via GUI or CLI mode with the following error:

Traceback (most recent call last):
  File "/Users/username/Documents/plex-poster-set-helper-main/plex_poster_set_helper.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

I'm running on python 3.13

**Comment by bbrown430** [comment]
They should be fixed by running `pip install -r requirements.txt `
