### ISSUE TITLE
Allow to input text file with links to sets

### ISSUE THREAD

**Issue by jl94x4** [bbrown430/plex-poster-set-helper#6]
Brilliant tool, I love it. Not an issue here but more of a feature request.

Would there be a way you can allow the tool to parse a txt file that is full of poster set links? I collect sets I use in a text file, one link per line. So being able to just do a command for the tool to read posters.txt would be absolutely brilliant.

**Comment by bbrown430** [comment]
Shouldn't be hard to implement, on my todo list

**Comment by bbrown430** [comment]
Latest commit adds this. Just enter 'bulk' in the first input, and then it will prompt for the path to the .txt file
